<?php

namespace App\Http\Controllers\Api\InventoryAPIs;

use App\Http\Controllers\Controller;
use App\Http\Resources\Inventory\DspResource;
use App\Models\DirectSupplyPermission;
use App\Models\DirectSupplyPermissionStatusSetting;
use App\Models\Product;
use App\Models\ProductBrand;
use App\Models\SupplyOrder;
use App\Services\Inventory_Services\DirectSupplyPermissionService;
use Exception;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Validator;

class DirectSupplyPermissionController extends Controller
{

    protected $dspService;
    public function __construct(DirectSupplyPermissionService $dspService)
    {
        $this->dspService = $dspService;
    }
    public function index(Request $request)
    {
        //list all dsp as manager or superadmin else only assigned qa_tester_id
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $user = auth('employee')->user();
        if ($user->hasRole('Inventory_Manager', 'employee') || $user->hasRole('superAdmin', 'employee')) {
            $query = DirectSupplyPermission::query()->whereNull('deleted_at');
        } else {
            $query = DirectSupplyPermission::query()
                ->whereNull('deleted_at')
                ->where('qa_tester_id', $user->id);
        }

        //Optional filter
        if ($request->has('status_id')) {
            $query->where('dsp_status_id', $request->status_id);
        }

        //Include relationships before executing query
        $query->with([
            'items',
            'items.item.product',
            'qaTester',
            'fromStore',
            'toStore',
            'purchaseRequest',
            'items.item.productStores',
            'supplyOrder'
        ]);
        $dsps = paginateOrGetAll($query, $request, [], []);

        $data = DspResource::collection($dsps['data']);

        return ResponseWithSuccessDataPaginated($lang, [
            'data' => $data,
            'meta' => $dsps['meta'] ?? null,
        ], 1);
    }
    public function show(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);

        $dsp = DirectSupplyPermission::find($id);
        if (!$dsp) {
            return respondError(
                $lang == 'en' ? 'Purchase order not found.' : 'أمر الشراء غير موجود.',
                404
            );
        }
        $dsp->load([
            'items',
            'items.item.product',
            'items.item.productStores',
            'qaTester',
            'fromStore',
            'toStore',
            'purchaseRequest',
            'supplyOrder'
        ]);
        $data = new DspResource($dsp);

        return ResponseWithSuccessData($lang, $data, 1);
    }

    public function createAutoGeneratedNumber(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $employee = auth('employee')->user();
        $soNumber = 'DSP-' . now()->format('Ymd') . '-' . str_pad(DirectSupplyPermission::count() + 1, 4, '0', STR_PAD_LEFT);

        $canUpdateNumber = $employee && $employee->can('update DspNumber');
        return ResponseWithSuccessData(
            $lang == 'en' ? 'Auto generated direct supply permission number.' : 'تم إنشاء رقم الإذن بالتوريد المباشر تلقائيًا.',
            [
                'supply_order_number' => $soNumber,
                'can_update_number' => $canUpdateNumber,
            ],
            1
        );
    }
    public function store(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $employee = auth('employee')->user();

        $validator = Validator::make($request->all(), [
            'date' => [
                'nullable',
                'date',
                'date_format:Y-m-d H:i:s',
                'after_or_equal:' . now()->format('Y-m-d H:i:s'),
            ],
            'from_store_id' => 'required|exists:stores,id',
            'to_store_id' => 'required|exists:stores,id',
            'linked_pr_id' => 'nullable|exists:purchase_requests,pr_number',
            'linked_so_id' => 'nullable|exists:supply_orders,order_number',
            'qa_tester_id' => 'nullable',
            'status' => [
                'nullable',
                'integer',
                'in:1,2',
            ],
            'items' => 'required|array|min:1',
            'items.*.category_id' => 'required|exists:categories,id',
            'items.*.item_id' => [
                'required',
                'exists:product_brands,id',
                // Custom validation rule to ensure item belongs to category
                function ($attribute, $value, $fail) use ($request) {
                    // Extract the index from items.*.item_id → e.g., items.0.item_id → 0
                    preg_match('/items\.(\d+)\.item_id/', $attribute, $matches);
                    $index = $matches[1] ?? null;

                    if ($index !== null) {
                        $categoryId = $request->items[$index]['category_id'] ?? null;

                        // Check if product_brand belongs to that category
                        $product = ProductBrand::where('id', $value)
                            ->first()->product_id;
                        $exists = Product::where('id', $product)->where('category_id', $categoryId)->exists();
                        if (! $exists) {
                            $fail( __('validation.custom.item_category_mismatch'));
                        }
                    }
                },
            ],
            'items.*.unit_id' => 'required|exists:units,id',
            'items.*.quantity' => 'required|numeric|min:0.01',
            'items.*.notes' => 'nullable|string',
        ]);

        if ($validator->fails()) {

            return respondError(($lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.'), 400, $validator->errors());
        }

        // // Custom validation for ordered_unit
        // if ($request->has('items')) {
        //     $productIds = array_column($request->input('items', []), 'item_id');
        //     $productBrands = ProductBrand::whereIn('product_id', $productIds)
        //         ->get()
        //         ->keyBy('product_id');
        //     foreach ($request->input('items', []) as $index => $item) {
        //         $productBrand = $productBrands->get($item['item_id']);
        //         // dd($productBrands, $item['item_id'], $request->input('items', []));
        //         $validUnits = array_filter([
        //             $productBrand->default_unit_id,
        //             $productBrand->base_unit_id,
        //         ]);

        //         if (!in_array($item['unit_id'], $validUnits)) {
        //             return respondError(
        //                 $lang == 'en' ? 'Invalid unit for product ' . $item['item_id'] : 'وحدة غير صالحة للمنتج ' . $item['item_id'],
        //                 400,
        //                 ['items.' . $index . '.unit_id' => $lang == 'en' ? 'The ordered unit must be the default or base unit for the selected product.' : 'يجب أن تكون الوحدة المطلوبة هي الوحدة الافتراضية أو الأساسية للمنتج المحدد.']
        //             );
        //         }
        //     }
        // }

        // Generate unique PO number (e.g., PO-20250702-0001)
        $dspNumber = 'DSP-' . now()->format('Ymd') . '-' . str_pad(DirectSupplyPermission::count() + 1, 4, '0', STR_PAD_LEFT);

        $request->merge(['dsp_number' => $dspNumber]);
        $request->merge(['lang' => $lang]);

        $dsp = $this->dspService->createDSP($request->all());
        $dsp->load(['items', 'creator', 'qaTester']);
        $data = new DspResource($dsp);
        return ResponseWithSuccessData(
            $lang,
            $data,
            1
        );
    }

    public function updateStatus(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        try {
            $dsp = DirectSupplyPermission::findOrFail($id);

            $validated = Validator::make($request->all(), [
                'dsp_status' => 'required|exists:direct_supply_permission_status_settings,id',
            ]);
            if ($validated->fails()) {

                return respondError(($lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.'), 400, $validated->errors());
            }
            $dsp_status = DirectSupplyPermissionStatusSetting::find($dsp->dsp_status_id);
            if (!$dsp_status) {
                return respondError(
                    $lang == 'en' ? 'DSP status not found.' : 'حالة أمر الشراء غير موجودة.',
                    404
                );
            }
            $dsp_previous = $dsp_status->previous_statuses;
            $dsp_next = $dsp_status->next_statuses;

            if ($request->dsp_status == $dsp->dsp_status_id) {
                return respondError(
                    $lang == 'en' ? 'Same status.' : 'نفس الحالة.',
                    400
                );
            }
            if ($dsp_previous != null && in_array($request->dsp_status, $dsp_previous)) {
                return respondError(
                    $lang == 'en' ? 'Not allowed to transition to a previous status.' : 'غير مسموح للانتقال لحاله سابقه للحاله الحاليه',
                    400
                );
            }
            if ($dsp_status->type == 'final' || !in_array($request->dsp_status, $dsp_next)) {
                return respondError(
                    $lang == 'en' ? 'Invalid status transition.' : 'الحاله ليست متاحه للانتقال لها من الحاله الحاليه.',
                    400
                );
            }
            $this->dspService->updateStatus($dsp, $request->dsp_status);

            $dsp->refresh();
            return ResponseWithSuccessData(
                $lang,
                new DspResource($dsp),
                1
            );
        } catch (ModelNotFoundException $e) {
            return respondError(
                $lang == 'en' ? 'Purchase order not found.' : 'أمر الشراء غير موجود.',
                404
            );
        } catch (Exception $e) {
            return respondError(
                $lang == 'en' ? 'An error occurred while updating DSP status.' : 'حدث خطأ أثناء تحديث حالة أمر الشراء.',
                500
            );
        }
    }

    public function update(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $employee = auth('employee')->user();

        $dsp = DirectSupplyPermission::findOrFail($id);
        $validator = Validator::make($request->all(), [
            'items' => 'required|array|min:1',
            'items.*.id' => 'required|exists:direct_supply_permission_items,id',
            'items.*.received_quantity' => 'required|numeric|min:0.01',
            'items.*.notes' => 'nullable|string',
            'items.*.has_added' => 'nullable|in:0,1',
            'items.*.has_issued' => 'nullable|in:0,1',
            'items.*.issues' => 'required_if:items.*.has_issued,1|array|min:1',
            'items.*.issues.*.issue_type_id' => 'required|exists:direct_supply_issue_types,id',
            'items.*.issues.*.unit_id' => 'nullable|exists:units,id',
            'items.*.issues.*.quantity' => 'required|numeric|min:0.01',
        ]);
        $validator->after(function ($validator) use ($request) {
            if ($request->has('items')) {
                foreach ($request->items as $index => $item) {
                    if (
                        isset($item['has_issued']) &&
                        $item['has_issued'] == 1 &&
                        (!isset($item['has_added']) || $item['has_added'] != 0)
                    ) {
                        $validator->errors()->add(
                            "items.$index.has_added",
                            "The has_added field must be 0 as there is an issue in item $index."
                        );
                    }
                }
            }
        });
        if ($validator->fails()) {
            return respondError(
                $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.',
                400,
                $validator->errors()
            );
        }
        $items = $request->items;

        $totalQuantity = 0;
        $totalReceived = 0;
        $allIssued = true;
        $allNoIssue = true;
        $anyIssued = false;
        $allAdded = true;
        $allNotAdded = true;

        foreach ($items as $item) {
            $totalQuantity += $item['received_quantity'];
            $totalReceived += $item['received_quantity'];

            if (($item['has_issued'] ?? 0) == 1) {
                $anyIssued = true;
                $allNoIssue = false;
            } else {
                $allIssued = false;
            }

            if (($item['has_added'] ?? 0) == 1) {
                $allNotAdded = false;
            } else {
                $allAdded = false;
            }
        }
        $status = null;
        // Compare total quantities and determine status
        if ($totalQuantity === $totalReceived) {

            if ($allNoIssue && $allNotAdded) {
                $status = 3; // all quantities equal, all not added, no issues
            } elseif ($allNoIssue && $allAdded) {
                $status = 9; // all quantities equal, all added, no issues
            } elseif ($anyIssued && !$allIssued) {
                $status = 6; // some items have issue, some not
            } elseif ($allIssued) {
                $status = 8; // all items have issue
            }
        }
        $request->merge(['status' => $status]);
        $request->merge(['lang' => $lang]);

        $updated = $this->dspService->updateDSP($dsp, $request->all());
        $updated->load(['items', 'creator', 'qaTester']);
        $data = new DspResource($updated);

        return ResponseWithSuccessData($lang, $data, 1);
    }
    public function listStatus(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $status = DirectSupplyPermissionStatusSetting::whereIn('id', [3, 4, 5, 7])->get();
        $data = $status->map(function ($item) {
            return [
                'id' => $item->id,
                'name' => $item->name,
            ];
        });
        return ResponseWithSuccessData($lang, $data, 1);
    }
}
