<?php

namespace App\Http\Controllers\Api\InventoryAPIs;

use App\Http\Controllers\Controller;
use App\Models\ProductBrand;
use App\Models\PurchaseRequest;
use App\Services\Inventory_Services\PurchaseRequestService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Spatie\Activitylog\Models\Activity;

class PurchaseRequestController extends Controller
{
    protected $purchaseRequestService;
    public function __construct(PurchaseRequestService $purchaseRequestService)
    {
        $this->purchaseRequestService = $purchaseRequestService;
    }
    public function index(Request $request)
    {
            $request->attributes->set('module', 'inventory');

        return $this->purchaseRequestService->index($request);
    }
    public function createAutoGeneratedNumber(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $employee = auth('employee')->user();

        // Call service
        $prNumber = $this->purchaseRequestService->generateAutoNumber();

        // Permission
        $canUpdateNumber = $employee && $employee->can('update PurchaseRequestNumber');

        return ResponseWithSuccessData(
            $lang === 'en'
                ? 'Auto generated purchase request number.'
                : 'تم إنشاء رقم طلب الشراء تلقائيًا.',
            [
                'purchase_request_number' => $prNumber,
                'can_update_number' => $canUpdateNumber,
            ],
            1
        );
    }

    public function store(Request $request)
    {
        return $this->purchaseRequestService->store($request);
    }
    public function update(Request $request, $id)
    {
        return $this->purchaseRequestService->update($request, $id);
    }
    public function approveOrReject(Request $request, $id)
    {
        return $this->purchaseRequestService->approveOrReject($request, $id);
    }
    public function show(Request $request, $id)
    {
            $request->attributes->set('module', 'inventory');

        return $this->purchaseRequestService->show($request, $id);
    }

   // Single ID route: /purchase-requests/{id}
public function delete(Request $request, $id)
{
    return $this->purchaseRequestService->deleteMultiple($request, $id);
}



    public function getLogs(Request $request)
    {
        try {
            $lang = $request->header('lang', 'ar');
            App::setLocale($lang);

            // Define the models you want logs for
            $allowedModels = [
                'App\\Models\\AuditType',
                'App\\Models\\Employee',
                'App\\Models\\Product',
                'App\\Models\\ProductBrand',
                'App\\Models\\ProductBrandCategoryColor',
                'App\\Models\\ProductBrandCategorySize',
                'App\\Models\\ProductBrandUnit',
                'App\\Models\\ProductColor',
                'App\\Models\\Zone',
                'App\\Models\\WasteReportItem',
                'App\\Models\\InventoryEmployee',
                'App\\Models\\WasteReport',
                'App\\Models\\Unit',
                'App\\Models\\StoreTransaction',
                'App\\Models\\StoreCategory',
                'App\\Models\\Store',
                'App\\Models\\Size',
                'App\\Models\\ReturnDsp',
                'App\\Models\\RejectReason',
                'App\\Models\\RejectPurchaseRequest',
                'App\\Models\\ReasonPurchaseRequest',
                // 'App\\Models\\ReasonList',
                'App\\Models\\ReasoneReturnDsp',
                'App\\Models\\RackShelf',
                'App\\Models\\PurchaseRequestItem',
                'App\\Models\\PurchaseRequest',
                'App\\Models\\PurchaseOrderStatus',
                'App\\Models\\PurchaseOrderReason',
                'App\\Models\\PurchaseOrderItem',
                'App\\Models\\PurchaseOrderIssues',
                'App\\Models\\ProductUnit',
                'App\\Models\\ProductTransaction',
                'App\\Models\\ProductStore',
                'App\\Models\\ProductSize',
                'App\\Models\\ProductOpeningBalance',
                'App\\Models\\ProductImage',
                'App\\Models\\ProductColor',
                'App\\Models\\ProductBrandUnit',
                'App\\Models\\ProductBrandCategorySize',
                'App\\Models\\ProductBrandCategoryColor',
                'App\\Models\\ProductBrand',
                'App\\Models\\Product',
                'App\\Models\\InventorySetting',
            ];

            // Start query
            $query = DB::table('activity_log')
                ->leftJoin('employees', 'employees.id', '=', 'activity_log.causer_id')
                ->select(
                    'activity_log.*',
                    'employees.first_name',
                    'employees.last_name'
                )
                ->whereIn('activity_log.subject_type', $allowedModels);

            // Apply filters
            if ($request->filled('user_id')) {
                $query->where('activity_log.causer_id', $request->user_id);
            }

            if ($request->filled('module')) {
                $query->where('activity_log.log_name', $request->module);
            }

            if ($request->filled('date')) {
                $query->whereDate('activity_log.created_at', $request->date);
            }


            $query->orderBy('activity_log.created_at', 'desc');

            $paginatedResult = paginateOrGetAll($query, $request);

            // Check empty data
            if ($paginatedResult['data']->isEmpty()) {
                return response()->json([
                    'status' => 1,
                    'message' => $lang == 'en' ? 'No logs found.' : 'لا توجد سجلات.',
                    'data' => [],
                    'meta' => $paginatedResult['meta']
                ]);
            }

            $grouped = $paginatedResult['data']->groupBy(function ($log) {
                return Carbon::parse($log->created_at)->format('Y-m-d');
            });

            $data = [];
            foreach ($grouped as $date => $items) {
                $formattedDate = Carbon::parse($date)->translatedFormat('l Y/m/d');

                $logsData = $items->map(function ($log) use ($lang) {
                    $userName = trim(($log->first_name ?? '') . ' ' . ($log->last_name ?? '')) ?: ($lang == 'en' ? 'System' : 'النظام');
                    $timeAgo = Carbon::parse($log->created_at)->diffForHumans();

                    return [
                        'id' => $log->id,
                        'module' => $log->log_name ?? '',
                        'description' => $log->description ?? '',
                        'user' => $userName,
                        'time' => $timeAgo,
                        'created_at' => Carbon::parse($log->created_at)->format('Y-m-d H:i'),
                    ];
                });

                $data[] = [
                    'date' => $formattedDate,
                    'logs' => $logsData->values(),
                ];
            }

            return response()->json([
                'status' => 1,
                'message' => $lang == 'en' ? 'Activity logs fetched successfully.' : 'تم جلب سجل النشاط بنجاح.',
                'data' => $data,
                'meta' => $paginatedResult['meta']
            ]);
        } catch (\Throwable $e) {
            return response()->json([
                'status' => 0,
                'message' => 'Error: ' . $e->getMessage(),
                'trace' => $e->getFile() . ':' . $e->getLine(),
            ], 500);
        }
    }
    public function getSuggestion(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);

        $product_brand_id = $request->input('product_brand_id');

        // Base query with relations
        $query = ProductBrand::with([
            'defaultUnit' => fn($q) => $q->withTrashed(),
            'productStores',
            'transactions',
            'product',
            'brand'
        ]);

        // Filter if product_brand_id is provided
        if ($product_brand_id) {
            $query->where('id', $product_brand_id);
        }

        $product_brands = $query->get();
        $suggestions = [];

        foreach ($product_brands as $brand) {
            // Get minimum limit (from productStores or brand itself)
            $min_limit = $brand->productStores->min('min_limit') ?? $brand->min_limit ?? 0;

            // Get current quantity in base unit
            $currentQty = getProductQuantity(
                $brand->id,
                'base',
                null,
                false
            )['quantity'];

            // If current quantity is below the minimum limit
            if ($currentQty < $min_limit) {
                $suggestedQty = $min_limit - $currentQty;

                $suggestion = [
                    'product_brand_id'   => $brand->id,
                    'product_brand_name' => trim(string: ($brand->product->name ?? '') . ' ' . ($brand->brand->name ?? '')),
                    'suggestions_count'  => $suggestedQty,
                    'current_quantity'   => $currentQty,
                    'min_limit'          => $min_limit,
                    'defaultUnit_id'     => $brand->defaultUnit->id ?? null,
                    'defaultUnit'        => $brand->defaultUnit->name ?? '',
                ];

                if ($product_brand_id) {
                    // Return a single object directly if filtered
                    return ResponseWithSuccessData($lang, [
                        'suggestion' => $suggestion
                    ], 1);
                }

                $suggestions[] = $suggestion;
            }
        }

        // If product_brand_id was provided but no suggestion found
        if ($product_brand_id) {
            return ResponseWithSuccessData($lang, [
                'suggestion' => null
            ], 1);
        }

        // Return all low stock suggestions
        return ResponseWithSuccessData($lang, [
            'suggestions' => $suggestions
        ], 1);
    }
}
