<?php

namespace App\Http\Controllers\Api\InventoryAPIs;

use App\Http\Controllers\Controller;
use App\Http\Resources\Inventory\SupplyOrderResource;
use Illuminate\Http\Request;
use App\Models\store;
use App\Models\SupplyReason;
use App\Models\SupplyOrder;
use App\Models\SupplyOrderReason;
use App\Services\Inventory_Services\SupplyOrderService;
use Illuminate\Support\Facades\Validator;

class SupplyOrderController extends Controller
{
    protected $supplyOrderService;

    public function __construct(SupplyOrderService $supplyOrderService)
    {
        $this->supplyOrderService = $supplyOrderService;
    }

    public function index(Request $request)
    {
        $lang = $request->header('lang', 'ar');

        $data = SupplyOrder::with(['fromStore', 'toStore', 'reason', 'items', 'items.productBrand', 'items.productBrand.product']);
        if ($request->has('status')) {
            $data->where('status', $request->status);
        }
        $orders = paginateOrGetAll($data, $request, [], []);
        $data = SupplyOrderResource::collection($orders['data']);
        return ResponseWithSuccessDataPaginated($lang, [
            'data' => $data,
            'meta' => $orders['meta'] ?? null,
        ], 1);
    }
    public function show(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');

        $order = SupplyOrder::with(['fromStore', 'toStore', 'reason', 'items', 'items.productBrand', 'items.productBrand.product'])->find($id);
        if (!$order) {
            $message = $lang == 'en'
                ? 'Supply order not found.'
                : 'لم يتم العثور على طلب التوريد.';
            return respondError($message, 404);
        }
        $data = new SupplyOrderResource($order);

        return ResponseWithSuccessData($lang, $data, 1);
    }
    public function createAutoGeneratedNumber(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $employee = auth('employee')->user();
        $soNumber = 'SO-' . now()->format('Ymd') . '-' . str_pad(SupplyOrder::count() + 1, 4, '0', STR_PAD_LEFT);

        $canUpdateNumber = $employee && $employee->can('update SupplyOrderNumber');
        return ResponseWithSuccessData(
            $lang == 'en' ? 'Auto generated supply order number.' : 'تم إنشاء رقم طلب التوريد تلقائيًا.',
            [
                'supply_order_number' => $soNumber,
                'can_update_number' => $canUpdateNumber,
            ],
            1
        );
    }


    public function store(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $employee = auth('employee')->user();

        $canUpdateNumber = $employee && $employee->can('update SupplyOrderNumber');

        $rules = [
            'from_store_id' => 'required|exists:stores,id',
            'to_store_id'   => 'required|exists:stores,id|different:from_store_id',
            'employee_id'   => 'required|exists:employees,id',
            'supply_reason_id' => 'required|exists:supply_order_reasons,id',
            'status'        => 'sometimes|in:draft,submitted',
            'type'          => 'required|in:one-time,periodic',
            'items'         => 'required|array|min:1',
            'items.*.product_brand_id' => 'required|exists:product_brands,id',
            'items.*.quantity'         => 'required|numeric|min:1',
            'items.*.unit_id'          => 'required|exists:units,id',
            'items.*.notes'            => 'nullable|string',
        ];

        // Add so_number rule dynamically based on permission
        if ($canUpdateNumber) {
            $rules['so_number'] = 'required|unique:supply_orders,order_number';
        } else {
            $rules['so_number'] = 'nullable|string'; // ignore uniqueness if no permission
        }

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            $message = $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق من الصحة.';
            return respondError($message, 400, $validator->errors());
        }
        $data = $request->all();

        // If user cannot update number OR sent duplicate number → generate a new one
        if (!$canUpdateNumber) {
            if (!empty($data['so_number'])) {
                $exists = SupplyOrder::where('order_number', $data['so_number'])->exists();
                if ($exists) {
                    $data['so_number'] = null;
                }
            }
        }

        // Generate order number if missing or null
        if (empty($data['so_number'])) {
            $data['order_number'] = 'SO-' . now()->format('Ymd') . '-' . str_pad(SupplyOrder::count() + 1, 4, '0', STR_PAD_LEFT);
        } else {
            $data['order_number'] = $data['so_number'];
        }
        $supplyOrder = $this->supplyOrderService->createSupplyOrder($request->all());

        return ResponseWithSuccessData($lang, $supplyOrder, 1);
    }
    // app/Http/Controllers/SupplyOrderController.php

    public function update(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        $validator = Validator::make($request->all(), [
            'from_store_id' => 'required|exists:stores,id',
            'to_store_id'   => 'required|exists:stores,id|different:from_store_id',
            'employee_id'   => 'required|exists:employees,id|',
            'supply_reason_id'  => 'required|exists:supply_order_reasons,id',
            'status'            => 'sometimes|in:draft,submitted',
            'type'              => 'required|in:one-time,periodic',
            'items'             => 'required|array|min:1',
            'items.*.product_brand_id'      => 'required|exists:product_brands,id',
            'items.*.quantity'  => 'required|numeric|min:1',
            'items.*.unit_id'      => 'required|exists:units,id',
            'items.*.notes'     => 'nullable|string',
        ]);
        if ($validator->fails()) {
            $message = $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق من الصحة.';
            return respondError($message, 400, $validator->errors());
        }

        $supplyOrder = SupplyOrder::find($id);
        if (!$supplyOrder) {
            $message = $lang == 'en' ? 'Supply order not found.' : 'لم يتم العثور على طلب التوريد.';
            return respondError($message, 404);
        }
        if ($supplyOrder->status !== 'draft') {
            $message =  $lang == 'en' ? "Only draft orders can be updated." : 'فقط يمكن تحديث الطلبات في حالة المسودة.';
            return respondErrorData($message, 400,  []);
        }
        $supplyOrder = $this->supplyOrderService->update($supplyOrder, $request->all());
        return ResponseWithSuccessData($lang, $supplyOrder->load('items'), 1);
    }

    public function submit(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');

        $supplyOrder = SupplyOrder::find($id);
        if (!$supplyOrder) {
            $message = $lang == 'en' ? 'Supply order not found.' : 'لم يتم العثور على طلب التوريد.';
            return respondError($message, 404, []);
        }
        if ($supplyOrder->status !== 'draft') {
            $message = $lang == 'en'
                ? "Only draft orders can be updated."
                : 'فقط يمكن تحديث الطلبات في حالة المسودة.';
            return respondErrorData($message, 400, []);
        }

        $this->supplyOrderService->submitSupplyOrder($supplyOrder);
        $supplyOrder->refresh();
        return ResponseWithSuccessData($lang, $supplyOrder, 1);
    }


    public function approve(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        $supplyOrder = SupplyOrder::find($id);
        if (!$supplyOrder) {
            $message = $lang == 'en' ? 'Supply order not found.' : 'لم يتم العثور على طلب التوريد.';
            return respondError($message, 404);
        }

        $supplyOrder =  $this->supplyOrderService->approve($supplyOrder);
        if (is_array($supplyOrder) && isset($supplyOrder['error'])) {
            $message = $lang == 'en' ? $supplyOrder['message_en'] : $supplyOrder['message_ar'];
            return respondError($message, $supplyOrder['code']);
        }
        return ResponseWithSuccessData($lang, $supplyOrder, 1);
    }


    public function reject(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');

        $validator = Validator::make($request->all(), [
            'reject_reason_id' => 'required|exists:supply_order_reject_reasons,id',
            'rejection_note' => 'nullable|string|max:1000',
        ]);
        if ($validator->fails()) {
            $message = $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق من الصحة.';
            return respondError($message, 400, $validator->errors());
        }
        $supplyOrder = SupplyOrder::find($id);
        if (!$supplyOrder) {
            $message = $lang == 'en' ? 'Supply order not found.' : 'لم يتم العثور على طلب التوريد.';
            return respondError($message, 404, []);
        }
      $result=  $this->supplyOrderService->reject($supplyOrder, $request->reject_reason_id, $request->rejection_note);
        if (is_array($result) && isset($result['error'])) {
            $message = $lang == 'en' ? $result['message_en'] : $result['message_ar'];
            return respondError($message, $result['code']);
        }
        $supplyOrder->refresh();
        return ResponseWithSuccessData($lang, $supplyOrder, 1);
    }
    public function destroy(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');

        $supplyOrder = SupplyOrder::find($id);
        if (!$supplyOrder) {
            $message = $lang == 'en' ? 'Supply order not found.' : 'لم يتم العثور على طلب التوريد.';
            return respondError($message, 404, []);
        }
        if ($supplyOrder->status != 'draft') {
            $message = $lang == 'en' ? 'Supply order cannot be deleted in draft status.' : 'لا يمكن حذف طلب التوريد في حالة المسودة.';
            return respondError($message, 400, []);
        }
        $this->supplyOrderService->destroy($supplyOrder);
        return ResponseWithSuccessData($lang, null, 1);
    }
}
