<?php

namespace App\Http\Controllers\Api\InventoryAPIs;

use App\Http\Controllers\Controller;
use App\Http\Resources\Inventory\DspResource;
use App\Http\Resources\Inventory\WasteReportResource;
use App\Models\DirectSupplyPermission;
use App\Models\DirectSupplyPermissionStatusSetting;
use App\Models\ProductBrand;
use App\Models\SupplyOrder;
use App\Models\WasteReport;
use App\Models\WasteReportItem;
use App\Services\Inventory_Services\DirectSupplyPermissionService;
use Exception;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class WasteReportController extends Controller
{

    public function index(Request $request)
    {
        //list all dsp as manager or superadmin else only assigned qa_tester_id
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $user = auth('employee')->user();
        if ($user->hasRole('Inventory_Manager', 'employee') || $user->hasRole('superAdmin', 'employee')) {
            $query = WasteReport::query()->whereNull('deleted_at');
        } else {
            $query = WasteReport::query()
                ->whereNull('deleted_at');
                //->where('employee_id', $user->id)->orWhere('first_quality_officer_id', $user->id)->orWhere('second_quality_officer_id', $user->id);
        }

        //Optional filter
        if ($request->has('status')) {
            $query->where('status', $request->status);
        }

        // //Include relationships before executing query
        $query->with([
            'secondQualityOfficer',
            'firstQualityOfficer',
            'employee',
            'store',
            'items'

        ]);
        $dsps = paginateOrGetAll($query, $request, [], []);

        $data = WasteReportResource::collection($dsps['data']);

        return ResponseWithSuccessDataPaginated($lang, [
            'data' => $data,
            'meta' => $dsps['meta'] ?? null,
        ], 1);
    }
    public function show(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);

        $dsp = WasteReport::find($id);
        if (!$dsp) {
            return respondError(
                $lang == 'en' ? 'waste report not found.' : ' محضر الاعدام غير موجود.',
                404
            );
        }
        $dsp->load([
            'secondQualityOfficer',
            'firstQualityOfficer',
            'employee',
            'store',
            'items',
            'items.productBrand.transactions'
        ]);
        $data = new WasteReportResource($dsp);

        return ResponseWithSuccessData($lang, $data, 1);
    }

    public function createAutoGeneratedNumber(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $employee = auth('employee')->user();
        $soNumber = 'WR-' . now()->format('Ymd') . '-' . str_pad(WasteReport::count() + 1, 4, '0', STR_PAD_LEFT);

        $canUpdateNumber = $employee && $employee->can('update wastreportnumber');
        return ResponseWithSuccessData(
            $lang == 'en' ? 'Auto generated direct supply permission number.' : 'تم إنشاء رقم الإذن بالتوريد المباشر تلقائيًا.',
            [
                'supply_order_number' => $soNumber,
                'can_update_number' => $canUpdateNumber,
            ],
            1
        );
    }
    public function store(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $employee = auth('employee')->user();

        $validator = Validator::make($request->all(), [
            'date' => [
                'nullable',
                'date_format:Y-m-d',
                'after_or_equal:' . now()->format('Y-m-d'),
            ],
            'time' => ['nullable', 'date_format:H:i:s'],
            'name' => 'required|string',
            'report_number' => 'nullable|string',
            'store_id' => 'required|exists:stores,id',
            'employee_id' => [
                'required',
                Rule::exists('employees', 'id')->where('flag', 'inventory'),
            ],
            //pending as will use in version 2
            // 'first_employee_id' => [
            //     'nullable',
            //     Rule::exists('employees', 'id')->where('flag', 'inventory'),
            // ],
            // 'second_employee_id' => [
            //     'nullable',
            //     Rule::exists('employees', 'id')->where('flag', 'inventory'),
            // ],
            'items' => 'required|array|min:1',
            'items.*.item_id' => 'required|exists:product_brands,id',
            'items.*.barcode' => [
                'required',
                Rule::exists('product_transactions', 'barcode')
                    ->where(function ($query) use ($request) {
                        // match barcode rows with the same product_brand_id
                        foreach ($request->items as $index => $item) {
                            $query->orWhere(function ($q) use ($item) {
                                $q->where('barcode', $item['barcode'])
                                    ->where('product_brand_id', $item['item_id']);
                            });
                        }
                    }),
            ],
            'items.*.unit_id' => 'required|exists:units,id',
            'items.*.quantity' => 'required|numeric|min:0.01',
            'items.*.reason_waste' => 'required|integer|exists:waste_reasons,id',
            'items.*.image' => 'required|file',
        ]);
        $validator->after(function ($validator) use ($request) {
            foreach ($request->items as $index => $item) {
                $barcode = $item['barcode'] ?? null;
                $productId = $item['item_id'] ?? null;
                $quantityRequested = $item['quantity'];

                // Get available stock
                $quantityData = getProductQuantity($productId, 'base', $barcode, null);
                $availableQuantity = $quantityData ?? 0;

                if ($quantityRequested > $availableQuantity) {
                    $message = __('validation.custom.items_quantity_exceeds_stock', [
                        'requested' => $quantityRequested,
                        'available' => $availableQuantity,
                    ]);

                    $validator->errors()->add("items.$index.quantity", $message);
                }
            }
        });

        if ($validator->fails()) {
            return respondError(
                $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.',
                400,
                $validator->errors()
            );
        }

        // Permission check for manual report number update
        $canUpdateNumber = $employee && $employee->can('update wastreportnumber');

        // Always generate a new auto number
        do {
            $nextId = WasteReport::max('id') + 1;
            $report_number = 'WR-' . now()->format('Ymd') . '-' . str_pad($nextId, 4, '0', STR_PAD_LEFT);
        } while (WasteReport::where('report_number', $report_number)->exists());

        // If the user does NOT have permission, override any manual input
        if (!$canUpdateNumber) {
            $request->merge(['report_number' => $report_number]);
        } else {
            // If user provided a custom number, check uniqueness
            if ($request->filled('report_number') && WasteReport::where('report_number', $request->report_number)->exists()) {
                return respondError(
                    $lang == 'en' ? 'Report number already exists.' : 'رقم التقرير موجود بالفعل.',
                    400
                );
            }

            // If user didn’t provide a number, use auto one
            $request->merge(['report_number' => $request->report_number ?? $report_number]);
        }

        $wasteReport = new WasteReport();
        $wasteReport->store_id = $request->store_id;
        $wasteReport->name = $request->name;
        $wasteReport->date = $request->date;
        $wasteReport->time = $request->time;
        $wasteReport->report_number = $request->report_number;
        //pending as will use in version 2

        // $wasteReport->first_quality_officer_id = $request->first_employee_id;
        // $wasteReport->second_quality_officer_id = $request->second_employee_id;
        $wasteReport->employee_id = $request->employee_id;
        $wasteReport->created_by = $employee->id;
        $wasteReport->save();

        foreach ($request->items as $index => $item) {
            $waste_item = new WasteReportItem();
            $waste_item->waste_report_id = $wasteReport->id;
            $waste_item->barcode = $item['barcode'];
            $waste_item->product_brand_id = $item['item_id'];
            $waste_item->unit_id = $item['unit_id'];
            $waste_item->waste_reason_id = $item['reason_waste'];
            $waste_item->quantity = $item['quantity'];
            $waste_item->status = 'pending';
            $waste_item->created_by = $employee->id;
            $waste_item->save();

            if ($request->hasFile("items.$index.image")) {
                $file = $request->file("items.$index.image");
                UploadFile('images/wasteReports', 'image', $waste_item, $file);
            }
        }

        return ResponseWithSuccessData(
            $lang,
            $lang == 'en'
                ? "Waste report added successfully with number: {$wasteReport->report_number}."
                : "تم إضافة تقرير الإعدام بنجاح برقم: {$wasteReport->report_number}.",
            1
        );
    }

    public function update(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $employee = auth('employee')->user();

        $wasteReport = WasteReport::find($id);
        if (!$wasteReport) {
            return respondError(
                $lang == 'en' ? 'Waste report not found.' : 'تقرير الهدر غير موجود.',
                404
            );
        }
        if ($wasteReport->status !== 'pending') {
            return respondError(
                $lang == 'en'
                    ? 'You can only update reports with pending status.'
                    : 'يمكن تعديل التقارير ذات الحالة معلقه فقط.',
                403
            );
        }

        $validator = Validator::make($request->all(), [
            // 'date' => [
            //     'nullable',
            //     'date_format:d-m-Y',
            //     'after_or_equal:' . now()->format('d-m-Y'),
            // ],

            // 'time' => [
            //     'nullable',
            //     'date_format:H:i:s',
            // ],
            'name' => 'required|string',
            'store_id' => 'required|exists:stores,id',
            'employee_id' => [
                'required',
                Rule::exists('employees', 'id')->where('flag', 'inventory'),
            ],
            //pending as will use in version 2
            // 'first_employee_id' => [
            //     'nullable',
            //     Rule::exists('employees', 'id')->where('flag', 'inventory'),
            // ],
            // 'second_employee_id' => [
            //     'nullable',
            //     Rule::exists('employees', 'id')->where('flag', 'inventory'),
            // ],
            'items' => 'required|array|min:1',
            'items.*.item_id' => 'required|exists:product_brands,id',
            'items.*.barcode' => [
                'required',
                Rule::exists('product_transactions', 'barcode')
                    ->where(function ($query) use ($request) {
                        // match barcode rows with the same product_brand_id
                        foreach ($request->items as $index => $item) {
                            $query->orWhere(function ($q) use ($item) {
                                $q->where('barcode', $item['barcode'])
                                    ->where('product_brand_id', $item['item_id']);
                            });
                        }
                    }),
            ],
            'items.*.unit_id' => 'required|exists:units,id',
            'items.*.quantity' => 'required|numeric|min:0.01',
            'items.*.reason_waste' => 'required|integer|exists:waste_reasons,id',
            'items.*.image' => 'nullable|file',
        ]);

        $validator->after(function ($validator) use ($request) {
            foreach ($request->items as $index => $item) {
                $barcode = $item['barcode'] ?? null;
                $productId = $item['item_id'] ?? null;
                $quantityRequested = $item['quantity'] ?? 0;

                // Get available stock
                $quantityData = getProductQuantity($productId, 'base', $barcode, null);
                $availableQuantity = $quantityData ?? 0;

                if ($quantityRequested > $availableQuantity) {
                    $message = __('validation.custom.items_quantity_exceeds_stock', [
                        'requested' => $quantityRequested,
                        'available' => $availableQuantity,
                    ]);

                    $validator->errors()->add("items.$index.quantity", $message);
                }
            }
        });


        if ($validator->fails()) {
            return respondError(
                $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.',
                400,
                $validator->errors()
            );
        }
        // if ($employee->id !== $wasteReport->employee_id && $employee->id !== $wasteReport->created_by) {
        //     return respondError(
        //         $lang == 'en'
        //             ? 'You are not authorized to update this waste report.'
        //             : 'غير مصرح لك بتعديل هذا التقرير.',
        //         403
        //     );
        // }
        // Update main report
        $wasteReport->store_id = $request->store_id;
        $wasteReport->name = $request->name;
        $wasteReport->date = $request->date;
        $wasteReport->time = $request->time;
        // $wasteReport->first_quality_officer_id = $request->first_employee_id;
        // $wasteReport->second_quality_officer_id = $request->second_employee_id;
        $wasteReport->employee_id = $request->employee_id;
        $wasteReport->updated_by = $employee->id;
        $wasteReport->save();

        // Delete old items (optional, or you can just update them)
        WasteReportItem::where('waste_report_id', $wasteReport->id)->delete();

        foreach ($request->items as $item) {
            $waste_item = new WasteReportItem();
            $waste_item->waste_report_id = $wasteReport->id;
            $waste_item->product_brand_id = $item['item_id'];
            $waste_item->unit_id = $item['unit_id'];
            $waste_item->waste_reason_id = $item['reason_waste'];
            $waste_item->quantity = $item['quantity'];
            $waste_item->status = 'pending';
            $waste_item->created_by = $employee->id;
            $waste_item->save();
            if (!empty($item['image']) && $request->hasFile('items.' . array_search($item, $request->items) . '.image')) {
                $file = $item['image'];
                UploadFile('images/wasteReports', 'image', $waste_item, $file);
            }
        }

        return ResponseWithSuccessData(
            $lang,
            $lang == 'en' ? 'Waste report updated successfully.' : 'تم تحديث تقرير الهدر بنجاح.',
            1
        );
    }

    public function changeStatus(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);

        $employee = auth('employee')->user();

        $validator = Validator::make($request->all(), [
            'status' => 'required|in:pending,Being Audited,rejected,confirmed',
        ]);

        if ($validator->fails()) {
            return respondError(
                $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.',
                400,
                $validator->errors()
            );
        }

        $wasteReport = WasteReport::find($id);

        if (!$wasteReport) {
            return respondError(
                $lang == 'en' ? 'Waste report not found.' : 'تقرير الهدر غير موجود.',
                404
            );
        }

        $currentStatus = $wasteReport->status;
        $newStatus = $request->status;
        if ($currentStatus === 'rejected') {
            return respondError(
                $lang == 'en'
                    ? 'A rejected report cannot change status.'
                    : 'لا يمكن تغيير حالة التقرير المرفوض.',
                403
            );
        }
        // Rule 1: If current status is pending → cannot change directly to confirmed
        if ($currentStatus === 'pending' && $newStatus === 'confirmed') {
            return respondError(
                $lang == 'en'
                    ? 'You cannot change directly from pending to confirmed.'
                    : 'لا يمكن التغيير مباشرةً من حالة معلق إلى تم الموافقة.',
                403
            );
        }

        // Rule 2: If current status is not pending → cannot change back to pending
        if ($currentStatus !== 'pending' && $newStatus === 'pending') {
            return respondError(
                $lang == 'en'
                    ? 'You cannot change back to pending once it has progressed.'
                    : 'لا يمكن العودة إلى حالة معلق بعد تغييرها.',
                403
            );
        }

        //Cannot confirm unless all items reviewed
        if ($newStatus === 'confirmed') {
            $unreviewedItemsCount = WasteReportItem::where('waste_report_id', $wasteReport->id)
                ->where('status', '!=', 'reviewed')
                ->count();

            if ($unreviewedItemsCount > 0) {
                return respondError(
                    $lang == 'en'
                        ? 'Cannot confirm this waste report until all items are reviewed.'
                        : 'لا يمكن تأكيد تقرير الإعدام قبل مراجعة جميع العناصر.',
                    403
                );
            }
        }

        $wasteReport->status = $newStatus;
        $wasteReport->updated_by = $employee->id;
        $wasteReport->save();
        if ($newStatus === 'rejected') {
            $items = WasteReportItem::where('waste_report_id', $wasteReport->id)->get();

            foreach ($items as $waste_item) {
                $waste_item->status = 'reviewed';
                $waste_item->updated_by = $employee->id;
                $waste_item->reviewed_employee_id = $employee->id;
                $waste_item->actual_quantity_wasted = 0;
                $waste_item->save();
            }
        }

        return ResponseWithSuccessData(
            $lang,
            null,
            1
        );
    }

    public function review(Request $request, $id)
    {
        $lang = $request->header('lang', 'ar');
        App::setLocale($lang);
        $employee = auth('employee')->user();

        $validator = Validator::make($request->all(), [
            'items' => 'required|array|min:1',
            'items.*.id' => 'required|exists:waste_report_items,id',
            'items.*.actual_quantity_wasted' => 'required|numeric|min:0',
            'items.*.waste_unit_id' => 'required|exists:units,id',
        ]);

        if ($validator->fails()) {
            return respondError(
                $lang == 'en' ? 'Validation Error.' : 'خطأ في التحقق.',
                400,
                $validator->errors()
            );
        }

        $wasteReport = WasteReport::find($id);

        if (!$wasteReport) {
            return respondError(
                $lang == 'en' ? 'Waste report not found.' : 'تقرير الإعدام غير موجود.',
                404
            );
        }

        $itemIds = collect($request->items)->pluck('id');
        $invalidItems = WasteReportItem::whereIn('id', $itemIds)
            ->where('waste_report_id', '!=', $wasteReport->id)
            ->pluck('id');

        if ($invalidItems->isNotEmpty()) {
            return respondError(
                $lang == 'en'
                    ? 'Some items do not belong to this waste report.'
                    : 'بعض العناصر لا تنتمي إلى تقرير الإعدام المحدد.',
                403
            );
        }

        // Block editing if rejected or confirmed
        if (in_array($wasteReport->status, ['rejected', 'confirmed'])) {
            return respondError(
                $lang == 'en'
                    ? 'This waste report has already been reviewed.'
                    : 'تمت مراجعة تقرير الإعدام من قبل.',
                400
            );
        }

        // Allow only if status is pending or Being Audited
        if (!in_array($wasteReport->status, ['Being Audited', 'pending'])) {
            return respondError(
                $lang == 'en'
                    ? 'You can only review items when the waste report is Being Audited or pending.'
                    : 'يمكنك مراجعة العناصر فقط عندما تكون حالة تقرير الإعدام "قيد المراجعة" أو "معلق".',
                400
            );
        }

        $updatedItems = [];

        foreach ($request->items as $itemData) {
            $item = WasteReportItem::where('id', $itemData['id'])
                ->where('waste_report_id', $wasteReport->id)
                ->first();

            if (!$item) continue;

            $item->actual_quantity_wasted = $itemData['actual_quantity_wasted'];
            $item->waste_unit_id = $itemData['waste_unit_id'];
            $item->status = 'reviewed';
            $item->reviewed_employee_id = $employee->id;
            $item->updated_by = $employee->id;
            $item->save();

            // Create Product Transaction (type = 'out')
            storeProductTransaction(
                $item->product_brand_id,
                $item->actual_quantity_wasted,
                $item->waste_unit_id,
                $item->barcode ?? null,
                $item->production_date ?? null,
                $item->expiration_date ?? null,
                'out',
                $employee,
                'waste_report_items',
                $item->id
            );

            $updatedItems[] = $item->id;
        }

        //Update waste report status based on item review progress
        $totalItems = WasteReportItem::where('waste_report_id', $wasteReport->id)->count();
        $reviewedItems = WasteReportItem::where('waste_report_id', $wasteReport->id)
            ->where('status', 'reviewed')
            ->count();

        $wasteReport->status = ($totalItems > 0 && $totalItems == $reviewedItems)
            ? 'confirmed'
            : 'Being Audited';
        $wasteReport->save();

        return ResponseWithSuccessData(
            $lang,
            $lang == 'en'
                ? 'Items reviewed successfully and waste report status updated.'
                : 'تمت مراجعة العناصر بنجاح وتحديث حالة تقرير الإعدام.',
            1
        );
    }

    public function destroy($id, Request $request)
    {
        $lang = $request->header('lang', 'ar');
        $employee = auth('employee')->user();

        $wasteReport = WasteReport::find($id);

        if (!$wasteReport) {
            return respondError(
                $lang == 'en' ? 'Waste report not found.' : 'تقرير الإعدام غير موجود.',
                404
            );
        }

        if ($wasteReport->status !== 'pending') {
            return respondError(
                $lang == 'en' ? 'Only pending reports can be deleted.' : 'يمكن حذف التقارير المعلقة فقط.',
                403
            );
        }

        // if ($wasteReport->created_by != $employee->id && $wasteReport->employee_id != $employee->id) {
        //     return respondError(
        //         $lang == 'en' ? 'You do not have permission to delete this report.' : 'ليس لديك صلاحية لحذف هذا التقرير.',
        //         403
        //     );
        // }

        $wasteReport->deleted_by = $employee->id;
        $wasteReport->save();

        WasteReportItem::where('waste_report_id', $wasteReport->id)->delete();

        $wasteReport->delete();
        return RespondWithSuccessMsg($lang == 'en'
            ? 'Waste report deleted successfully.'
            : 'تم حذف تقرير الإعدام بنجاح.');
    }
}
