<?php

namespace App\Http\Controllers\Api\ProcurementAPIS;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\Controller;
use App\Models\PurchaseRequest;
use App\Services\Inventory_Services\PurchaseRequestService;
use Illuminate\Support\Facades\DB;

class PurchaseRequestController extends Controller
{
    protected $purchaseRequestService;
    public function __construct(PurchaseRequestService $purchaseRequestService)
    {
        $this->purchaseRequestService = $purchaseRequestService;
    }
    public function index(Request $request)
    {
        // Set module attribute here
        $request->attributes->set('module', 'purchase');

        // Call the service
        return $this->purchaseRequestService->index($request);
    }
    public function createAutoGeneratedNumber(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        // Call service
        $prNumber = $this->purchaseRequestService->generateAutoNumber();

        return ResponseWithSuccessData(
            $lang === 'en'
                ? 'Auto generated purchase request number.'
                : 'تم إنشاء رقم طلب الشراء تلقائيًا.',
            [
                'purchase_request_number' => $prNumber,
            ],
            1
        );
    }


    public function store(Request $request)
    {
        return $this->purchaseRequestService->store($request);
    }
    public function update(Request $request, $id)
    {
        return $this->purchaseRequestService->update($request, $id);
    }
    public function approveOrReject(Request $request, $id)
    {
        return $this->purchaseRequestService->approveOrReject($request, $id);
    }
    public function show(Request $request, $id)
    {
        $request->attributes->set('module', 'purchase');

        return $this->purchaseRequestService->show($request, $id);
    }

    public function deleteMultiple(Request $request)
    {
        return $this->purchaseRequestService->deleteMultiple($request);
    }

    public function showProducts(Request $request)
    {
        return $this->purchaseRequestService->showProducts($request);
    }
        public function updatedamyProductStatus(Request $request,$id)
    {
        return $this->purchaseRequestService->updatedamyProductStatus($request,$id);
    }
}
