<?php

namespace App\Http\Controllers\Api\ProcurementAPIS;

use App\Services\ProcurementServices\PurchaseOrderService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PurchaseOrderController extends Controller
{
    protected $purchaseOrderService;
    public function __construct(PurchaseOrderService $purchaseOrderService)
    {
        $this->purchaseOrderService = $purchaseOrderService;
    }
    public function index(Request $request)
    {
        // Set module attribute here
        $request->attributes->set('module', 'purchase');

        // Call the service
        return $this->purchaseOrderService->index($request);
    }
    public function createAutoGeneratedNumber(Request $request)
    {
        $lang = $request->header('lang', 'ar');
        // Call service
        $prNumber = $this->purchaseOrderService->generateAutoNumber();

        return ResponseWithSuccessData(
            $lang === 'en'
                ? 'Auto generated purchase request number.'
                : 'تم إنشاء رقم طلب الشراء تلقائيًا.',
            [
                'purchase_request_number' => $prNumber,
            ],
            1
        );
    }


    public function store(Request $request)
    {
        return $this->purchaseOrderService->store($request);
    }
    public function update(Request $request, $id)
    {
        return $this->purchaseOrderService->update($request, $id);
    }

    public function show(Request $request, $id)
    {
        $request->attributes->set('module', 'purchase');

        return $this->purchaseOrderService->show($request, $id);
    }

    public function deleteMultiple(Request $request,$ids = null)
    {
        return $this->purchaseOrderService->deleteMultiple($request,$ids);
    }

    public function acceptPM(Request $request,$id)
    {
        return $this->purchaseOrderService->approvePOByPM($request, $id);
    }
        public function acceptFM(Request $request,$id)
    {
        return $this->purchaseOrderService->approvePOByFM($request,$id);
    }
        public function reject(Request $request,$id)
    {
        return $this->purchaseOrderService->reject($request,$id);
    }

    public function mergePOs(Request $request)
    {
        return $this->purchaseOrderService->mergePOs($request);
    }
}
