<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Spatie\Permission\PermissionRegistrar;

class DashboardPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        //keys permissions 
        $permissions = [
            "view dashboard",
            "view actionbacklogs",
            "create actionbacklogs",
            "update actionbacklogs",
            "delete actionbacklogs",
            "view advances",
            "create advances",
            "update advances",
            "delete advances",
            "view advance_requests",
            "create advance_requests",
            "update advance_requests",
            "delete advance_requests",
            "view advance_settings",
            "create advance_settings",
            "update advance_settings",
            "delete advance_settings",
            "view branches",
            "create branches",
            "update branches",
            "delete branches",
            "view branch_coupon",
            "create branch_coupon",
            "update branch_coupon",
            "delete branch_coupon",
            "view branch_discount",
            "create branch_discount",
            "update branch_discount",
            "delete branch_discount",
            "view branch_recipe",
            "create branch_recipe",
            "update branch_recipe",
            "delete branch_recipe",
            "view brands",
            "create brands",
            "update brands",
            "delete brands",
            "view cashier_machines",
            "create cashier_machines",
            "update cashier_machines",
            "delete cashier_machines",
            "view cashier_machine_logs",
            "create cashier_machine_logs",
            "update cashier_machine_logs",
            "delete cashier_machine_logs",
            "view categories",
            "create categories",
            "update categories",
            "delete categories",
            "view client_addresses",
            "create client_addresses",
            "update client_addresses",
            "delete client_addresses",
            "view client_details",
            "create client_details",
            "update client_details",
            "delete client_details",
            "view colors",
            "create colors",
            "update colors",
            "delete colors",
            "view countries",
            "create countries",
            "update countries",
            "delete countries",
            "view coupons",
            "create coupons",
            "update coupons",
            "delete coupons",
            "view cuisines",
            "create cuisines",
            "update cuisines",
            "delete cuisines",
            "view delays",
            "create delays",
            "update delays",
            "delete delays",
            "view delay_deductions",
            "create delay_deductions",
            "update delay_deductions",
            "delete delay_deductions",
            "view delay_times",
            "create delay_times",
            "update delay_times",
            "delete delay_times",
            "view delivery_settings",
            "create delivery_settings",
            "update delivery_settings",
            "delete delivery_settings",
            "view departments",
            "create departments",
            "update departments",
            "delete departments",
            "view discounts",
            "create discounts",
            "update discounts",
            "delete discounts",
            "view dishes",
            "create dishes",
            "update dishes",
            "delete dishes",
            "view dish_addons",
            "create dish_addons",
            "update dish_addons",
            "delete dish_addons",
            "view dish_categories",
            "create dish_categories",
            "update dish_categories",
            "delete dish_categories",
            "view dish_details",
            "create dish_details",
            "update dish_details",
            "delete dish_details",
            "view dish_discount",
            "create dish_discount",
            "update dish_discount",
            "delete dish_discount",
            "view einvoices",
            "view einvoice_settings",
            "create einvoice_settings",
            "update einvoice_settings",
            "view employees",
            "create employees",
            "update employees",
            "delete employees",
            "view employee_floor_partitions",
            "create employee_floor_partitions",
            "update employee_floor_partitions",
            "delete employee_floor_partitions",
            "view employee_opening_balances",
            "create employee_opening_balances",
            "update employee_opening_balances",
            "delete employee_opening_balances",
            "view employee_schedules",
            "create employee_schedules",
            "update employee_schedules",
            "delete employee_schedules",
            "view excuses",
            "create excuses",
            "update excuses",
            "delete excuses",
            "view excuse_requests",
            "create excuse_requests",
            "update excuse_requests",
            "delete excuse_requests",
            "view excuse_settings",
            "create excuse_settings",
            "update excuse_settings",
            "delete excuse_settings",
            "view floors",
            "create floors",
            "update floors",
            "delete floors",
            "view floor_partitions",
            "create floor_partitions",
            "update floor_partitions",
            "delete floor_partitions",
            "view gifts",
            "create gifts",
            "update gifts",
            "delete gifts",
            "view ingredients",
            "create ingredients",
            "update ingredients",
            "delete ingredients",
            "view leave_nationals",
            "create leave_nationals",
            "update leave_nationals",
            "delete leave_nationals",
            "view leave_requests",
            "create leave_requests",
            "update leave_requests",
            "delete leave_requests",
            "view leave_settings",
            "create leave_settings",
            "update leave_settings",
            "delete leave_settings",
            "view leave_types",
            "create leave_types",
            "update leave_types",
            "delete leave_types",
            "view lines",
            "create lines",
            "update lines",
            "delete lines",
            "view menu",
            "create menu",
            "update menu",
            "delete menu",
            "view notifications",
            "create notifications",
            "update notifications",
            "delete notifications",
            "view offers",
            "create offers",
            "update offers",
            "delete offers",
            "view opening_balance",
            "create opening_balance",
            "update opening_balance",
            "delete opening_balance",
            "view orders",
            "create orders",
            "update orders",
            "delete orders",
            "view order_addons",
            "create order_addons",
            "update order_addons",
            "delete order_addons",
            "view order_details",
            "create order_details",
            "update order_details",
            "delete order_details",
            "view order_products",
            "create order_products",
            "update order_products",
            "delete order_products",
            "view order_refunds",
            "create order_refunds",
            "update order_refunds",
            "delete order_refunds",
            "view order_trackings",
            "create order_trackings",
            "update order_trackings",
            "delete order_trackings",
            "view order_transactions",
            "create order_transactions",
            "update order_transactions",
            "delete order_transactions",
            "view overtime_settings",
            "create overtime_settings",
            "update overtime_settings",
            "delete overtime_settings",
            "view overtime_types",
            "create overtime_types",
            "update overtime_types",
            "delete overtime_types",
            "view payrolls",
            "create payrolls",
            "update payrolls",
            "delete payrolls",
            "view penalties",
            "create penalties",
            "update penalties",
            "delete penalties",
            "view penalty_deductions",
            "create penalty_deductions",
            "update penalty_deductions",
            "delete penalty_deductions",
            "view penalty_reasons",
            "create penalty_reasons",
            "update penalty_reasons",
            "delete penalty_reasons",
            "view permissions",
            "create permissions",
            "update permissions",
            "delete permissions",
            "view point_products",
            "create point_products",
            "update point_products",
            "delete point_products",
            "view point_systems",
            "create point_systems",
            "update point_systems",
            "delete point_systems",
            "view point_transactions",
            "create point_transactions",
            "update point_transactions",
            "delete point_transactions",
            "view positions",
            "create positions",
            "update positions",
            "delete positions",
            "view products",
            "create products",
            "update products",
            "delete products",
            "view product_colors",
            "create product_colors",
            "update product_colors",
            "delete product_colors",
            "view product_images",
            "create product_images",
            "update product_images",
            "delete product_images",
            "view product_limit",
            "create product_limit",
            "update product_limit",
            "delete product_limit",
            "view product_sizes",
            "create product_sizes",
            "update product_sizes",
            "delete product_sizes",
            "view product_transactions",
            "create product_transactions",
            "update product_transactions",
            "delete product_transactions",
            "view product_transaction_logs",
            "create product_transaction_logs",
            "update product_transaction_logs",
            "delete product_transaction_logs",
            "view product_units",
            "create product_units",
            "update product_units",
            "delete product_units",
            "view purchase_invoices",
            "create purchase_invoices",
            "update purchase_invoices",
            "delete purchase_invoices",
            "view purchase_invoices_details",
            "create purchase_invoices_details",
            "update purchase_invoices_details",
            "delete purchase_invoices_details",
            "view recipes",
            "create recipes",
            "update recipes",
            "delete recipes",
            "view recipe_images",
            "create recipe_images",
            "update recipe_images",
            "delete recipe_images",
            "view roles",
            "create roles",
            "update roles",
            "delete roles",
            "view settings",
            "create settings",
            "update settings",
            "delete settings",
            "view shelves",
            "create shelves",
            "update shelves",
            "delete shelves",
            "view shifts",
            "create shifts",
            "update shifts",
            "delete shifts",
            "view sizes",
            "create sizes",
            "update sizes",
            "delete sizes",
            "view stores",
            "create stores",
            "update stores",
            "delete stores",
            "view store_categories",
            "create store_categories",
            "update store_categories",
            "delete store_categories",
            "view store_transactions",
            "create store_transactions",
            "update store_transactions",
            "delete store_transactions",
            "view store_transaction_details",
            "create store_transaction_details",
            "update store_transaction_details",
            "delete store_transaction_details",
            "view tables",
            "create tables",
            "update tables",
            "delete tables",
            "view table_reservations",
            "create table_reservations",
            "update table_reservations",
            "delete table_reservations",
            "view timetables",
            "create timetables",
            "update timetables",
            "delete timetables",
            "view units",
            "create units",
            "update units",
            "delete units",
            "view users",
            "create users",
            "update users",
            "delete users",
            "view user_gifts",
            "create user_gifts",
            "update user_gifts",
            "delete user_gifts",
            "view vendors",
            "create vendors",
            "update vendors",
            "delete vendors",
            "view logos",
            "create logos",
            "update logos",
            "delete logos",
            "view sliders",
            "create sliders",
            "update sliders",
            "delete sliders",
            "view terms",
            "create terms",
            "update terms",
            "delete terms",
            "view privacies",
            "create privacies",
            "update privacies",
            "delete privacies",
            "view returns",
            "create returns",
            "update returns",
            "delete returns",
            "view discount_dishes",
            "view offerDetails",
            "create offerDetails",
            "update offerDetails",
            "delete offerDetails",
            "create faqs",
            "view faqs",
            "update faqs",
            "delete faqs",
            "view rates",
            "create rates",
            "update rates",
            "delete rates",
            "view branch_menu_categories",
            "view branch_menus",
            "create branch_menus",
            "update branch_menus",
            "delete branch_menus",
            "create branch_menu_categories",
            "update branch_menu_categories",
            "delete branch_menu_categories",
            "view report_best_seller_dishes",
            "view addon_categories",
            "print purchase_invoice",
            "edit addon_categorie",
            "view units_products",
            "delete addon_categories",
            "print advances",
            "print invoice",
            "view addons",
            "view branch_menu_addons",
            "create branch_menu_addons",
            "update branch_menu_addons",
            "delete branch_menu_addons",
            "view branch_menu_sizes",
            "create branch_menu_sizes'",
            "update branch_menu_sizes",
            "delete branch_menu_sizes",
            "view clients_reports",
            "view purchasing_reports",
            "view report_most_customer_place_order",
            "create order_settings",
            "update order_settings",
            "view order_settings",
            "active branch_menu_categories",
            "active branch_menus",
            "active branch_menu_addons",
            "active branch_menu_sizes",
            "restore addon_categories",
            "print orders",
            "download orders",
            "update addons",
            "delete addons",
            "restore addons",
            "create addons",
            "restore cuisines",
            "print purchase_invoices",
            "import employess",
            "save report_pdf",
            "detail report_orders",
            "view branch_menu_category_addons",
            "create branch_menu_category_addons",
            "update branch_menu_category_addons",
            "changestatus branch_menu_category_addons",
            "detail report_best_seller_dishes",
            "view report_branches",
            "detail report_branches",
            "view report_orders",
            "change status orders",
            "create addon_categories",
            "view vehicle_settings",
            "update vehicle_settings",
            "allowPort einvoices",
            "print einvoices",
            "view officer_assign_setting",
            "create officer_assign_setting",
            "update officer_assign_setting",
            "view einvoices_superadmin",
            "view cities",
            "create cities",
            "update cities",
            "delete cities",
            "view regions",
            "create regions",
            "update regions",
            "delete regions",
            "view company_profile_setting",
            "create company_profile_setting",
            "update company_profile_setting",
            "delete company_profile_setting",
            "view business_activity",
            "create business_activity",
            "update business_activity",
            "delete business_activity",
            "create cashPaymentSetting",
            "view cashPaymentSetting",
            "update cashPaymentSetting",
            "delete cashPaymentSetting",
            "view report_cashier_balances",
            "detail report_cashier_balances",
            "view report_delivery_orders",
            "view waiter_request",
            "view complaints",
            "update complaints",
            "delete complaints",
            "view hanging-orders",
            "update hanging-orders",
            "delete hanging-orders",
            "create payment_policies",
            "view payment_policies",
            "update payment_policies",
            "view payment_reservation_policies",
            "update payment_reservation_policies",
            "delete payment_policies",
            "view report_rates",
            "detail report_rates",
            "view report_feedbacks",
            "detail report_feedbacks",
            "view branch_settings",
            "update branch_settings",
            "delete branch_settings",
            "create branch_settings",
            "show units",
            "view companyProfileSettings",
            "update addon_categories",
            "view report_table_reservations",
            "detail report_table_reservations",
            "aml",
            "view report_booking_revenue",
            "detail report_booking_revenue",
            "view report_booking_cancellation",
            "detail report_booking_cancellation",
            "privacy",
            "view cancellation_reasons",
            "create cancellation_reasons",
            "update cancellation_reasons",
            "delete cancellation_reasons",
            "view waiter_table_service_report",
            "detail waiter_table_service_report",
            "create vehicles",
            "update vehicles",
            "view vehicles",
            "delete vehicles",
            "view report_waiter_requests",
            "details report_waiter_requests",
            "view delivery_order_report",
            "detail delivery_order_report",
            "view report_hanging_orders",
            "detail report_hanging_orders",
            "view delivery_earnings_payments_report",
            "detail delivery_earnings_payments_report",
            "view report_cashier_balance_transactions",
            "detail report_cashier_balance_transactions",
            "view delivery_performance_metrics_report",
            "detail delivery_performance_metrics_report",
            "view report_kitchen_performance",
            "detail report_kitchen_performance",
            "view report_cashier_performance",
            "detail report_cashier_performance",
            "view report_customer_service_delivery_orders",
            "detail report_customer_service_delivery_orders",
            "view ethnic_backgrounds",
            "create ethnic_backgrounds",
            "update ethnic_backgrounds",
            "delete ethnic_backgrounds",
            "view bank_names",
            "create bank_names",
            "update bank_names",
            "delete bank_names",
            "view marital_statuses",
            "view employee_status",
            "create employee_status",
            "update employee_status",
            "delete employee_status",
            "view university",
            "create university",
            "update university",
            "delete university",
            "view education_level",
            "create education_level",
            "update education_level",
            "delete education_level",
            "view filed_of_study",
            "create filed_of_study",
            "update filed_of_study",
            "delete filed_of_study",
            "view military_service_statuses",
            "view job_types",
            "create job_types",
            "update job_types",
            "delete job_types",
            "create applications positions",
            "update applications positions",
            "view applications answers",
            "update applications answers",
            "create marital_statuses",
            "update marital_statuses",
            "delete marital_statuses",
            "view violations",
            "view violation_types",
            "delete violations",
            "update violations",
            "create violations",
            "delete violation_types",
            "create violation_types",
            "view leave_setting_positions",
            "create military_service_statuses",
            "update military_service_statuses",
            "delete military_service_statuses",
            "view currencies",
            "create currencies",
            "update currencies",
            "delete currencies",
            "view nationalities",
            "create nationalities",
            "update nationalities",
            "delete nationalities",
            "view payment_types",
            "create payment_types",
            "update payment_types",
            "delete payment_types",
            "view payment_frequencies",
            "create payment_frequencies",
            "update payment_frequencies",
            "delete payment_frequencies"
        ];

        $insertedIds = [];

        foreach ($permissions as $perm) {
            // Try to create English and Arabic names simply
            $enName = $perm;
            $arName = $this->autoTranslate($perm);

            $permission = Permission::firstOrCreate(
                [
                    'name'       => $perm,
                    'guard_name' => 'employee',
                ],
                [
                    'name_en'   => $perm,
                    'name_ar'   => $this->autoTranslate($perm),
                    'is_global' => 0,
                    'is_active' => 1,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );

            $insertedIds[] = $permission->id;
        }

        // Assign all permissions to module_id = 2
        foreach ($insertedIds as $permissionId) {
            DB::table('module_permission')->updateOrInsert([
                'module_id' => 5,
                'permission_id' => $permissionId,
            ]);
        }
        // Assign all permissions to roles `Branch_Manager` and `superAdmin`
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // get role and permissions
        $branchManager = Role::where('name', 'Branch_Manager')->where('guard_name', 'employee')->first();
        $superAdmin = Role::where('name', 'superAdmin')->where('guard_name', 'employee')->first();

        $permissionsModels = Permission::whereIn('id', $insertedIds)->get();

        // Replace old permissions for branch manager
        if ($branchManager) {
            $branchManager->syncPermissions($permissionsModels); // old removed, new assigned
        }

        // Add permissions to superAdmin without removing old ones
        if ($superAdmin) {
            $superAdmin->givePermissionTo($permissionsModels);
        }
    }

    /**
     * Quick Arabic translation helper (optional)
     */
    private function autoTranslate(string $text): string
    {
        $map = [
            'view' => 'عرض',
            'create' => 'إضافة',
            'update' => 'تحديث',
            'delete' => 'حذف',
            'approve' => 'موافقة',
            'reject' => 'رفض',
            'changeStatus' => 'تغيير الحالة',
            'approveOrReject' => 'موافقه او الرفض',
            'restore' => 'استعادة',
            'submit' => 'إرسال',
            'assign' => 'تعيين',
            'print' => 'طباعة',
            'download' => 'تحميل',
            'import' => 'استيراد',
            'export' => 'تصدير',
            'save' => 'حفظ',
            'detail' => 'تفاصيل',
            'details' => 'تفاصيل',
            'active' => 'تفعيل',
            'changestatus' => 'تغيير الحالة',
            'allowPort' => 'السماح بالمنفذ',
            'show' => 'عرض',
            'privacy' => 'الخصوصية',
            'edit' => 'تعديل'
        ];

        $objectMap = [
            'dashboard' => 'لوحة التحكم',
            'actionbacklogs' => 'سجلات الإجراءات',
            'advances' => 'السلف',
            'advance_requests' => 'طلبات السلف',
            'advance_settings' => 'إعدادات السلف',
            'branches' => 'الفروع',
            'branch_coupon' => 'كوبونات الفرع',
            'branch_discount' => 'خصومات الفرع',
            'branch_recipe' => 'وصفات الفرع',
            'brands' => 'العلامات التجارية',
            'cashier_machines' => 'ماكينات الصراف',
            'cashier_machine_logs' => 'سجلات ماكينات الصراف',
            'categories' => 'الفئات',
            'client_addresses' => 'عناوين العملاء',
            'client_details' => 'تفاصيل العملاء',
            'colors' => 'الألوان',
            'countries' => 'الدول',
            'coupons' => 'الكوبونات',
            'cuisines' => 'المطابخ',
            'delays' => 'التأخيرات',
            'delay_deductions' => 'خصومات التأخير',
            'delay_times' => 'أوقات التأخير',
            'delivery_settings' => 'إعدادات التوصيل',
            'departments' => 'الأقسام',
            'discounts' => 'الخصومات',
            'dishes' => 'الأطباق',
            'dish_addons' => 'الإضافات',
            'dish_categories' => 'فئات الأطباق',
            'dish_details' => 'تفاصيل الأطباق',
            'dish_discount' => 'خصومات الأطباق',
            'einvoices' => 'الفواتير الإلكترونية',
            'einvoice_settings' => 'إعدادات الفواتير الإلكترونية',
            'employees' => 'الموظفين',
            'employee_floor_partitions' => 'تقسيمات أرضية الموظفين',
            'employee_opening_balances' => 'الأرصدة الافتتاحية للموظفين',
            'employee_schedules' => 'جداول الموظفين',
            'excuses' => 'الأعذار',
            'excuse_requests' => 'طلبات الأعذار',
            'excuse_settings' => 'إعدادات الأعذار',
            'floors' => 'الأدوار',
            'floor_partitions' => 'تقسيمات الأرضية',
            'gifts' => 'الهدايا',
            'ingredients' => 'المكونات',
            'leave_nationals' => 'الإجازات الوطنية',
            'leave_requests' => 'طلبات الإجازة',
            'leave_settings' => 'إعدادات الإجازة',
            'leave_types' => 'أنواع الإجازات',
            'lines' => 'الخطوط',
            'menu' => 'القائمة',
            'notifications' => 'الإشعارات',
            'offers' => 'العروض',
            'opening_balance' => 'الرصيد الافتتاحي',
            'orders' => 'الطلبات',
            'order_addons' => 'إضافات الطلبات',
            'order_details' => 'تفاصيل الطلبات',
            'order_products' => 'منتجات الطلبات',
            'order_refunds' => 'مرتجعات الطلبات',
            'order_trackings' => 'تتبع الطلبات',
            'order_transactions' => 'معاملات الطلبات',
            'overtime_settings' => 'إعدادات العمل الإضافي',
            'overtime_types' => 'أنواع العمل الإضافي',
            'payrolls' => 'كشوف المرتبات',
            'penalties' => 'الجزاءات',
            'penalty_deductions' => 'خصومات الجزاءات',
            'penalty_reasons' => 'أسباب الجزاءات',
            'permissions' => 'الصلاحيات',
            'point_products' => 'منتجات النقاط',
            'point_systems' => 'أنظمة النقاط',
            'point_transactions' => 'معاملات النقاط',
            'positions' => 'المناصب',
            'products' => 'المنتجات',
            'product_colors' => 'ألوان المنتجات',
            'product_images' => 'صور المنتجات',
            'product_limit' => 'حد المنتج',
            'product_sizes' => 'مقاسات المنتجات',
            'product_transactions' => 'معاملات المنتجات',
            'product_transaction_logs' => 'سجلات معاملات المنتجات',
            'product_units' => 'وحدات المنتجات',
            'purchase_invoices' => 'فواتير الشراء',
            'purchase_invoices_details' => 'تفاصيل فواتير الشراء',
            'recipes' => 'الوصفات',
            'recipe_images' => 'صور الوصفات',
            'roles' => 'الأدوار',
            'settings' => 'الإعدادات',
            'shelves' => 'الرفوف',
            'shifts' => 'الورديات',
            'sizes' => 'المقاسات',
            'stores' => 'المخازن',
            'store_categories' => 'فئات المخازن',
            'store_transactions' => 'معاملات المخازن',
            'store_transaction_details' => 'تفاصيل معاملات المخازن',
            'tables' => 'الطاولات',
            'table_reservations' => 'حجوزات الطاولات',
            'timetables' => 'الجداول الزمنية',
            'units' => 'الوحدات',
            'users' => 'المستخدمين',
            'user_gifts' => 'هدايا المستخدمين',
            'vendors' => 'الموردين',
            'logos' => 'الشعارات',
            'sliders' => 'السلايدرز',
            'terms' => 'الشروط',
            'privacies' => 'الخصوصيات',
            'returns' => 'المرتجعات',
            'discount_dishes' => 'أطباق الخصم',
            'offerDetails' => 'تفاصيل العروض',
            'faqs' => 'الأسئلة الشائعة',
            'rates' => 'التقييمات',
            'branch_menu_categories' => 'فئات قوائم الفروع',
            'branch_menus' => 'قوائم الفروع',
            'branch_menu_addons' => 'إضافات قوائم الفروع',
            'branch_menu_sizes' => 'مقاسات قوائم الفروع',
            'addon_categories' => 'فئات الإضافات',
            'addons' => 'الإضافات',
            'clients_reports' => 'تقارير العملاء',
            'purchasing_reports' => 'تقارير الشراء',
            'order_settings' => 'إعدادات الطلبات',
            'vehicle_settings' => 'إعدادات المركبات',
            'officer_assign_setting' => 'إعدادات تعيين الضباط',
            'cities' => 'المدن',
            'regions' => 'المناطق',
            'company_profile_setting' => 'إعدادات ملف الشركة',
            'business_activity' => 'النشاط التجاري',
            'cashPaymentSetting' => 'إعدادات الدفع النقدي',
            'waiter_request' => 'طلب النادل',
            'complaints' => 'الشكاوى',
            'hanging-orders' => 'الطلبات المعلقة',
            'payment_policies' => 'سياسات الدفع',
            'payment_reservation_policies' => 'سياسات حجز الدفع',
            'cancellation_reasons' => 'أسباب الإلغاء',
            'vehicles' => 'المركبات',
            'ethnic_backgrounds' => 'الخلفيات العرقية',
            'bank_names' => 'أسماء البنوك',
            'employee_status' => 'حالة الموظف',
            'university' => 'الجامعة',
            'education_level' => 'المستوى التعليمي',
            'filed_of_study' => 'مجال الدراسة',
            'military_service_statuses' => 'حالات الخدمة العسكرية',
            'job_types' => 'أنواع الوظائف',
            'violations' => 'المخالفات',
            'violation_types' => 'أنواع المخالفات',
            'leave_setting_positions' => 'إعدادات الإجازة للمناصب',
            'currencies' => 'العملات',
            'nationalities' => 'الجنسيات',
            'payment_types' => 'أنواع الدفع',
            'payment_frequencies' => 'تكرارات الدفع',
            'units_products' => 'وحدات المنتجات',
            'companyProfileSettings' => 'إعدادات ملف الشركة',
            'einvoices_superadmin' => 'الفواتير الإلكترونية للمشرف',
            'report_best_seller_dishes' => 'تقرير الأطباق الأكثر مبيعاً',
            'report_most_customer_place_order' => 'تقرير العملاء الأكثر طلباً',
            'report_branches' => 'تقرير الفروع',
            'report_orders' => 'تقرير الطلبات',
            'report_cashier_balances' => 'تقرير أرصدة الصرافين',
            'report_delivery_orders' => 'تقرير طلبات التوصيل',
            'report_rates' => 'تقرير التقييمات',
            'report_feedbacks' => 'تقرير التغذية الراجعة',
            'report_table_reservations' => 'تقرير حجوزات الطاولات',
            'report_booking_revenue' => 'تقرير إيرادات الحجوزات',
            'report_booking_cancellation' => 'تقرير إلغاء الحجوزات',
            'waiter_table_service_report' => 'تقرير خدمة طاولات النادل',
            'report_waiter_requests' => 'تقرير طلبات النادل',
            'delivery_order_report' => 'تقرير طلبات التوصيل',
            'report_hanging_orders' => 'تقرير الطلبات المعلقة',
            'delivery_earnings_payments_report' => 'تقرير أرباح ومدفوعات التوصيل',
            'report_cashier_balance_transactions' => 'تقرير معاملات أرصدة الصرافين',
            'delivery_performance_metrics_report' => 'تقرير مؤشرات أداء التوصيل',
            'report_kitchen_performance' => 'تقرير أداء المطبخ',
            'report_cashier_performance' => 'تقرير أداء الصرافين',
            'marital_statuses' => 'الحالات الاجتماعية',
            'report_customer_service_delivery_orders' => 'تقرير طلبات خدمة العملاء والتوصيل'
        ];

        $arabic = $text;
        foreach ($map as $en => $ar) {
            if (str_contains($arabic, $en)) {
                $arabic = str_replace($en, $ar, $arabic);
                break;
            }
        }

        // $arabic = str_replace(['_', '-'], ' ', $arabic);

        foreach ($objectMap as $en => $ar) {
            if (str_contains($arabic, $en)) {
                $arabic = str_replace($en, $ar, $arabic);
            }
        }

        return trim($arabic);
    }
}
